# Generated by Django 3.2 on 2022-01-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipient',
            new_name='Send_Email',
        ),
    ]
