# Generated by Django 3.2 on 2022-01-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0002_rename_recipient_send_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_email',
            old_name='username',
            new_name='Name',
        ),
    ]
